# Generated by Django 5.2.4 on 2026-02-08 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_manage_patients', models.BooleanField(default=True)),
                ('can_manage_documents', models.BooleanField(default=True)),
                ('can_run_audits', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_admins', to='agencies.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['name'], name='agencies_ag_name_28738a_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['slug'], name='agencies_ag_slug_a791c8_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['is_active'], name='agencies_ag_is_acti_5f838a_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['created_at'], name='agencies_ag_created_0d0844_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyadmin',
            unique_together={('agency', 'user')},
        ),
    ]
