# Generated by Django 5.2.13 on 2026-04-14 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyadmin',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_admins', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='agencyadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_admin_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['name'], name='agencies_ag_name_28738a_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['slug'], name='agencies_ag_slug_a791c8_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['is_active'], name='agencies_ag_is_acti_5f838a_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['created_at'], name='agencies_ag_created_0d0844_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyadmin',
            unique_together={('agency', 'user')},
        ),
    ]
