# Generated by Django 5.2.13 on 2026-04-14 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedAuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=20)),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='assigned_report_docs/')),
                ('uploaded_document_name', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('election_statement', 'Election Statement'), ('cti_initial', 'CTI - Initial'), ('cti_recertification', 'CTI - Recertification'), ('rn_assessment', 'RN Initial Assessment'), ('comprehensive_assessment', 'Comprehensive Assessment'), ('plan_of_care', 'Plan of Care'), ('f2f_encounter', 'Face-to-Face Encounter'), ('clinical_notes', 'Clinical Notes'), ('physician_orders', 'Physician Orders'), ('other', 'Other')], max_length=30)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_mb', models.FloatField()),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField()),
                ('extraction_method', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document_type', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(help_text='Priority order (1 = highest)')),
                ('recommendation', models.TextField()),
                ('expected_outcome', models.TextField()),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(help_text='Patient identifier', max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('audit_type', models.CharField(choices=[('admission', 'Admission Audit'), ('recertification', 'Recertification Audit'), ('follow_up', 'Follow-up Audit'), ('complaint', 'Complaint-driven Audit')], max_length=20)),
                ('frameworks', models.JSONField(default=list, help_text='List of frameworks applied')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_compliance_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=10, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_number', models.IntegerField(help_text='Check number from 40 High-Risk Checks')),
                ('category', models.CharField(choices=[('A', 'Admission – Election & Rights'), ('B', 'Certification of Terminal Illness'), ('C', 'Eligibility & Clinical Support'), ('D', 'Assessments & Plan of Care'), ('E', 'Recertification & Face-to-Face')], max_length=1)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('finding_title', models.CharField(max_length=255)),
                ('finding_description', models.TextField()),
                ('evidence_from_document', models.TextField(blank=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity', 'check_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionGuidance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immediate_action', models.TextField(help_text='What needs to be done immediately')),
                ('responsible_party', models.CharField(choices=[('RN', 'Registered Nurse'), ('PHYSICIAN', 'Physician'), ('SOCIAL_WORKER', 'Social Worker'), ('CHAPLAIN', 'Chaplain'), ('ADMIN', 'Administrator'), ('QA', 'QA/Compliance Officer')], max_length=20)),
                ('timeline', models.CharField(help_text='Urgency timeframe', max_length=100)),
                ('template_suggestion', models.TextField(blank=True, help_text='Optional template language')),
            ],
            options={
                'verbose_name_plural': 'Correction Guidance',
            },
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('IMMEDIATE', 'Immediate Action Required'), ('URGENT', 'Urgent'), ('ROUTINE', 'Routine')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework', models.CharField(choices=[('CMS', 'CMS Hospice CoPs'), ('CHAP', 'CHAP Standards'), ('HHSC', 'Texas HHSC'), ('JOINT_COMMISSION', 'Joint Commission'), ('ACHC', 'ACHC')], max_length=20)),
                ('citation', models.CharField(help_text='Citation code (e.g., §418.22)', max_length=50)),
                ('description', models.TextField(help_text='Full regulatory text')),
            ],
            options={
                'ordering': ['framework', 'citation'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analyzed_document_names', models.JSONField(default=list, help_text='List of filenames of documents that were analyzed')),
                ('report_markdown', models.TextField(help_text='Full Markdown compliance audit report generated by Mistral AI')),
                ('ai_model_used', models.CharField(default='open-mistral-nemo', max_length=100)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Fail', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician_document', models.FileField(blank=True, help_text='Document submitted by the clinician for this report', null=True, upload_to='clinician_report_docs/')),
                ('clinician_document_name', models.CharField(blank=True, help_text='Original filename of the clinician-submitted document', max_length=255)),
                ('clinician_document_status', models.CharField(choices=[('pending', 'Document Pending'), ('submitted', 'Document Submitted')], default='pending', help_text='Whether clinician has submitted a document for this report', max_length=20)),
                ('clinician_document_submitted_at', models.DateTimeField(blank=True, help_text='When the clinician submitted the document', null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_results', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
