# Generated by Django 5.2.4 on 2026-02-08 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(help_text='Patient identifier', max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('audit_type', models.CharField(choices=[('admission', 'Admission Audit'), ('recertification', 'Recertification Audit'), ('follow_up', 'Follow-up Audit'), ('complaint', 'Complaint-driven Audit')], max_length=20)),
                ('frameworks', models.JSONField(default=list, help_text='List of frameworks applied')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_compliance_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=10, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(help_text='Priority order (1 = highest)')),
                ('recommendation', models.TextField()),
                ('expected_outcome', models.TextField()),
                ('audit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai.auditsession')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('election_statement', 'Election Statement'), ('cti_initial', 'CTI - Initial'), ('cti_recertification', 'CTI - Recertification'), ('rn_assessment', 'RN Initial Assessment'), ('comprehensive_assessment', 'Comprehensive Assessment'), ('plan_of_care', 'Plan of Care'), ('f2f_encounter', 'Face-to-Face Encounter'), ('clinical_notes', 'Clinical Notes'), ('physician_orders', 'Physician Orders'), ('other', 'Other')], max_length=30)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_mb', models.FloatField()),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField()),
                ('extraction_method', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai.auditsession')),
            ],
            options={
                'ordering': ['document_type', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_number', models.IntegerField(help_text='Check number from 40 High-Risk Checks')),
                ('category', models.CharField(choices=[('A', 'Admission – Election & Rights'), ('B', 'Certification of Terminal Illness'), ('C', 'Eligibility & Clinical Support'), ('D', 'Assessments & Plan of Care'), ('E', 'Recertification & Face-to-Face')], max_length=1)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('finding_title', models.CharField(max_length=255)),
                ('finding_description', models.TextField()),
                ('evidence_from_document', models.TextField(blank=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=255)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL)),
                ('audit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='ai.auditsession')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='ai.auditdocument')),
            ],
            options={
                'ordering': ['-severity', 'check_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionGuidance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immediate_action', models.TextField(help_text='What needs to be done immediately')),
                ('responsible_party', models.CharField(choices=[('RN', 'Registered Nurse'), ('PHYSICIAN', 'Physician'), ('SOCIAL_WORKER', 'Social Worker'), ('CHAPLAIN', 'Chaplain'), ('ADMIN', 'Administrator'), ('QA', 'QA/Compliance Officer')], max_length=20)),
                ('timeline', models.CharField(help_text='Urgency timeframe', max_length=100)),
                ('template_suggestion', models.TextField(blank=True, help_text='Optional template language')),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction_guidance', to='ai.compliancefinding')),
            ],
            options={
                'verbose_name_plural': 'Correction Guidance',
            },
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('IMMEDIATE', 'Immediate Action Required'), ('URGENT', 'Urgent'), ('ROUTINE', 'Routine')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='ai.auditsession')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework', models.CharField(choices=[('CMS', 'CMS Hospice CoPs'), ('CHAP', 'CHAP Standards'), ('HHSC', 'Texas HHSC'), ('JOINT_COMMISSION', 'Joint Commission'), ('ACHC', 'ACHC')], max_length=20)),
                ('citation', models.CharField(help_text='Citation code (e.g., §418.22)', max_length=50)),
                ('description', models.TextField(help_text='Full regulatory text')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='ai.compliancefinding')),
            ],
            options={
                'ordering': ['framework', 'citation'],
            },
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['patient_id'], name='ai_auditses_patient_6d3f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['created_by'], name='ai_auditses_created_b4faf1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['status'], name='ai_auditses_status_8e47f8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['created_at'], name='ai_auditses_created_32d702_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['audit_session'], name='ai_complian_audit_s_aeecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['severity'], name='ai_complian_severit_b283b4_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['status'], name='ai_complian_status_02c575_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['assigned_to'], name='ai_complian_assigne_6796f5_idx'),
        ),
    ]
