# Generated by Django 5.2.13 on 2026-04-14 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_initial'),
        ('ai', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='assignedauditreport',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audit_reports', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='assignedauditreport',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ai.aianalysisresult'),
        ),
        migrations.AddField(
            model_name='assignedauditreport',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedauditreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditdocument',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='auditdocument',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_sessions', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditrecommendation',
            name='audit_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai.auditsession'),
        ),
        migrations.AddField(
            model_name='auditdocument',
            name='audit_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai.auditsession'),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_findings', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='audit_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='ai.auditsession'),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='ai.auditdocument'),
        ),
        migrations.AddField(
            model_name='correctionguidance',
            name='finding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction_guidance', to='ai.compliancefinding'),
        ),
        migrations.AddField(
            model_name='redflag',
            name='audit_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='ai.auditsession'),
        ),
        migrations.AddField(
            model_name='regulatorycitation',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='ai.compliancefinding'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['agency'], name='ai_aianalys_agency__e548ef_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['patient'], name='ai_aianalys_patient_ae68e0_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['created_by'], name='ai_aianalys_created_f6a784_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedauditreport',
            index=models.Index(fields=['agency'], name='ai_assigned_agency__b218d5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedauditreport',
            index=models.Index(fields=['assigned_to'], name='ai_assigned_assigne_7bd42c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedauditreport',
            index=models.Index(fields=['assigned_by'], name='ai_assigned_assigne_f10350_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['patient_id'], name='ai_auditses_patient_6d3f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['created_by'], name='ai_auditses_created_b4faf1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['agency'], name='ai_auditses_agency__bc832b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['status'], name='ai_auditses_status_8e47f8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['created_at'], name='ai_auditses_created_32d702_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['audit_session'], name='ai_complian_audit_s_aeecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['agency'], name='ai_complian_agency__afbdf5_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['severity'], name='ai_complian_severit_b283b4_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['status'], name='ai_complian_status_02c575_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['assigned_to'], name='ai_complian_assigne_6796f5_idx'),
        ),
    ]
