# Generated by Django 5.2.11 on 2026-02-21 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auditdocument_agency'),
        ('patients', '0002_patient_agency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analyzed_document_names', models.JSONField(default=list, help_text='List of filenames of documents that were analyzed')),
                ('report_markdown', models.TextField(help_text='Full Markdown compliance audit report generated by Mistral AI')),
                ('ai_model_used', models.CharField(default='open-mistral-nemo', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_results', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
