# Generated by Django 5.2 on 2026-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_chart_intake_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='ai_analysis_agency__eb077a_idx',
            old_name='ai_analysis_agency__idx',
        ),
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='ai_analysis_patient_ccf70d_idx',
            old_name='ai_analysis_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='ai_analysis_created_3468a4_idx',
            old_name='ai_analysis_created_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisjob',
            new_name='ai_analysis_status_2ac00c_idx',
            old_name='ai_analysis_status_idx',
        ),
        migrations.RenameIndex(
            model_name='chartintakejob',
            new_name='ai_chartint_agency__14b356_idx',
            old_name='ai_chartint_agency_i_6f472a_idx',
        ),
        migrations.RenameIndex(
            model_name='chartintakejob',
            new_name='ai_chartint_created_f89f84_idx',
            old_name='ai_chartint_created__5d7c69_idx',
        ),
        migrations.RenameIndex(
            model_name='chartintakejob',
            new_name='ai_chartint_status_cbc9cf_idx',
            old_name='ai_chartint_status_9a6f55_idx',
        ),
        migrations.RenameIndex(
            model_name='chartintakejob',
            new_name='ai_chartint_created_bb2572_idx',
            old_name='ai_chartint_created__f08845_idx',
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='document_ids',
            field=models.JSONField(default=list, help_text='List of AuditDocument UUID strings included in this job'),
        ),
    ]
