# Generated by Django 5.2.4 on 2026-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aianalysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='status',
            field=models.CharField(default='Fail', help_text='Pass or Fail status based on findings', max_length=10),
        ),
    ]
