# Generated by Django 5.2.4 on 2026-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aianalysisresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisresult',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Fail', max_length=10),
        ),
    ]
