# Generated by GPT-5.2 on 2026-04-23

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def _extract_response_format(prompt_text: str) -> str:
    """
    Extract the shared response format section from the main compliance prompt.
    We intentionally store this separately so new prompts keep the same output schema.
    """
    if not prompt_text:
        return ""
    start_key = "## RESPONSE FORMAT"
    end_key = "## FINAL INSTRUCTIONS"
    start = prompt_text.find(start_key)
    if start == -1:
        return ""
    end = prompt_text.find(end_key, start)
    if end == -1:
        end = len(prompt_text)
    return prompt_text[start:end].strip()


def forwards(apps, schema_editor):
    PromptTemplate = apps.get_model("ai", "PromptTemplate")

    # Remove legacy default that is no longer used.
    PromptTemplate.objects.filter(identifier="patient_intake_extractor").delete()

    # Mark the seeded compliance prompt as main + locked and store its response format.
    main = PromptTemplate.objects.filter(identifier="compliance_auditor").first()
    if main:
        response_format = main.response_format or _extract_response_format(main.prompt_text)
        PromptTemplate.objects.filter(pk=main.pk).update(
            prompt_group="compliance_auditor",
            is_main=True,
            is_locked=True,
            response_format=response_format,
            is_active=True,
        )

    # Ensure all other prompts fall into compliance group for now (legacy behavior),
    # but deactivate them to satisfy "only one active prompt" rule.
    PromptTemplate.objects.exclude(identifier="compliance_auditor").update(
        prompt_group="compliance_auditor",
        is_main=False,
        is_locked=False,
        is_active=False,
    )


def backwards(apps, schema_editor):
    PromptTemplate = apps.get_model("ai", "PromptTemplate")
    PromptTemplate.objects.update(
        prompt_group="compliance_auditor",
        is_main=False,
        is_locked=False,
        response_format="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0006_prompttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttemplate",
            name="prompt_group",
            field=models.CharField(
                choices=[("compliance_auditor", "Compliance Auditor")],
                db_index=True,
                default="compliance_auditor",
                help_text="Logical prompt group used to select the active prompt at runtime.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="response_format",
            field=models.TextField(
                blank=True,
                help_text="Shared output format/schema instructions used for all prompts in the group.",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="is_main",
            field=models.BooleanField(
                default=False,
                help_text="Marks the default main prompt for this group.",
            ),
        ),
        migrations.AddField(
            model_name="prompttemplate",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="When locked, non-superadmins can only view.",
            ),
        ),
        migrations.AlterModelOptions(
            name="prompttemplate",
            options={"ordering": ["-is_main", "name"]},
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AddConstraint(
            model_name="prompttemplate",
            constraint=models.UniqueConstraint(
                fields=("prompt_group",),
                condition=Q(("is_active", True)),
                name="ai_prompttemplate_unique_active_per_group",
            ),
        ),
    ]

