# Generated by Django 5.2 on 2026-04-12 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('ai', '0008_add_clinician_document_to_ai_result'),
        ('patients', '0003_alter_patient_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_results', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='assignedauditreport',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audit_reports', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_sessions', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_findings', to='agencies.agency'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['agency'], name='ai_aianalys_agency__e548ef_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['patient'], name='ai_aianalys_patient_ae68e0_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['created_by'], name='ai_aianalys_created_f6a784_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedauditreport',
            index=models.Index(fields=['agency'], name='ai_assigned_agency__b218d5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedauditreport',
            index=models.Index(fields=['assigned_to'], name='ai_assigned_assigne_7bd42c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedauditreport',
            index=models.Index(fields=['assigned_by'], name='ai_assigned_assigne_f10350_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['agency'], name='ai_auditses_agency__bc832b_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefinding',
            index=models.Index(fields=['agency'], name='ai_complian_agency__afbdf5_idx'),
        ),
    ]
