# Generated by Django 5.2.4 on 2026-02-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('users', '0002_add_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='agencies.agency'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('agency_admin', 'Agency Admin'), ('qa_compliance', 'QA/Compliance'), ('clinical_leadership', 'Clinical Leadership'), ('clinician', 'Clinician')], default='clinician', max_length=20),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
    ]
